[profile.debug]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold", "-Zcodegen-backend=cranelift"]

[profile.release]
strip = true
lto = true
codegen-units = 1
opt-level = 3


[profile.dev.build-override]
opt-level = 3
